export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const result = await pool.query(`
      SELECT c.*, 
        (SELECT COUNT(*) FROM "Product" p WHERE p.category = c.name AND p."organizationId" = $1) as "productCount",
        (SELECT string_agg(p.name, ', ') FROM "Product" p WHERE p.category = c.name AND p."organizationId" = $1 LIMIT 10) as "productsList"
      FROM "Category" c
      WHERE c.id = $2
    `, [session.organizationId, params.id])

    if (result.rows.length === 0) {
      return NextResponse.json({ error: 'Category not found' }, { status: 404 })
    }

    const category = result.rows[0]

    const html = `<!DOCTYPE html>
<html>
<head>
  <title>Category Report - ${category.name}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { text-align: center; border-bottom: 3px solid #db2777; padding-bottom: 20px; margin-bottom: 30px; }
    .company { font-size: 28px; font-weight: bold; color: #db2777; }
    .title { font-size: 20px; color: #6b7280; margin-top: 5px; }
    .category-name { font-size: 32px; font-weight: bold; text-align: center; color: #111827; margin: 30px 0; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 30px 0; }
    .info-card { padding: 20px; border: 2px solid #e5e7eb; border-radius: 12px; text-align: center; }
    .info-label { font-size: 14px; color: #6b7280; margin-bottom: 8px; }
    .info-value { font-size: 24px; font-weight: bold; color: #db2777; }
    .products-list { margin-top: 30px; padding: 20px; background: #f9fafb; border-radius: 12px; }
    .products-title { font-weight: bold; margin-bottom: 10px; }
    .footer { margin-top: 50px; text-align: center; color: #9ca3af; font-size: 12px; }
    @media print {
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="company">IntelliWavve</div>
    <div class="title">Category Report</div>
  </div>
  
  <div class="category-name">${category.name}</div>
  
  <div class="info-grid">
    <div class="info-card">
      <div class="info-label">Total Products</div>
      <div class="info-value">${category.productCount || 0}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Created Date</div>
      <div class="info-value" style="font-size: 18px;">${new Date(category.createdAt).toLocaleDateString('en-KE')}</div>
    </div>
  </div>
  
  <div class="products-list">
    <div class="products-title">Products in this category:</div>
    <div>${category.productsList || 'No products yet'}</div>
  </div>
  
  <div class="footer">
    <p>Generated by IntelliWavve WaveCore ERP</p>
    <p>${new Date().toLocaleString('en-KE')}</p>
  </div>
  
  <script>window.print();</script>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="category-${category.name}.html"`
      }
    })
  } catch (error) {
    console.error('Category PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}