export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { pool } from '@/lib/wavecore/db'
import { requireTenant } from '@/lib/wavecore/auth'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const result = await pool.query(
      'SELECT * FROM "WorkOrder" WHERE id = $1 AND "organizationId" = $2',
      [params.id, session.organizationId]
    )

    if (result.rows.length === 0) return NextResponse.json({ error: 'Not found' }, { status: 404 })
    const wo = result.rows[0]

    const html = '<!DOCTYPE html><html><head><title>Work Order - ' + wo.number + '</title>' +
      '<style>body{font-family:Arial;padding:40px;max-width:800px;margin:0 auto}' +
      '.header{text-align:center;border-bottom:3px solid #7c3aed;padding-bottom:20px;margin-bottom:30px}' +
      '.company{font-size:28px;font-weight:bold;color:#7c3aed}' +
      '.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:30px 0}' +
      '.card{padding:20px;border:2px solid #e5e7eb;border-radius:12px;text-align:center}' +
      '.label{font-size:12px;color:#6b7280;text-transform:uppercase}' +
      '.value{font-size:22px;font-weight:bold;color:#7c3aed;margin-top:8px}' +
      '.footer{margin-top:40px;text-align:center;color:#9ca3af;font-size:12px}' +
      '</style></head><body>' +
      '<div class="header"><div class="company">WaveCore ERP</div><p>Work Order</p></div>' +
      '<div class="grid">' +
      '<div class="card"><div class="label">Number</div><div class="value">' + wo.number + '</div></div>' +
      '<div class="card"><div class="label">Type</div><div class="value">' + (wo.type || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">Status</div><div class="value">' + (wo.status || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">Quantity</div><div class="value">' + wo.quantity + '</div></div>' +
      '<div class="card"><div class="label">Completed</div><div class="value">' + (wo.completedQty || 0) + '</div></div>' +
      '<div class="card"><div class="label">Priority</div><div class="value">' + (wo.priority || 'N/A') + '</div></div>' +
      '</div>' +
      '<div class="footer"><p>Generated by WaveCore ERP</p><p>' + new Date().toLocaleString('en-KE') + '</p></div>' +
      '<script>window.print();</script></body></html>'

    return new NextResponse(html, {
      headers: { 'Content-Type': 'text/html' }
    })
  } catch (error) {
    return NextResponse.json({ error: 'Failed' }, { status: 500 })
  }
}