'use client'

import { useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { FileText, Download, Loader2, CheckCircle, Sparkles, BarChart3 } from 'lucide-react'
import { Button } from '@/components/ui/button'

export default function AIReportsPage() {
  const [reportType, setReportType] = useState('')
  const [generating, setGenerating] = useState(false)
  const [report, setReport] = useState('')

  const reportTypes = [
    { name: 'Financial Summary', icon: FileText, desc: 'Revenue, expenses, profit' },
    { name: 'Sales Analysis', icon: BarChart3, desc: 'Top products, customers' },
    { name: 'Inventory Report', icon: FileText, desc: 'Stock levels, value' },
    { name: 'Customer Report', icon: FileText, desc: 'Customer demographics' },
  ]

  const handleGenerate = () => {
    if (!reportType) return
    setGenerating(true)
    setReport('')
    setTimeout(() => {
      setReport(`# ${reportType}\n\nGenerated by WaveCore AI Copilot\n\n## Summary\n\nThis is an AI-generated ${reportType.toLowerCase()} based on your current business data.\n\n## Key Metrics\n\n- Revenue (MTD): KSh 0.00\n- Active Customers: 0\n- Products: 0\n\n## Recommendations\n\n1. Continue tracking business data for more insights\n2. Use analytics for deeper analysis\n3. Set up automated reports\n\n---\nGenerated: ${new Date().toLocaleString()}`)
      setGenerating(false)
    }, 2000)
  }

  const handleDownload = () => {
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = `${reportType.toLowerCase().replace(' ', '-')}.txt`; a.click()
  }

  return (
    <div className="min-h-screen bg-neutral-50 dark:bg-neutral-950">
      <header className="sticky top-0 z-40 bg-white/95 backdrop-blur-xl border-b">
        <div className="flex items-center justify-between px-4 h-16">
          <Link href="/wavecore-erp/ai" className="flex items-center gap-3">
            <Image src="/images/Wavecore.jpeg" alt="WaveCore" width={40} height={40} className="rounded-xl object-cover" />
            <span className="font-bold">WaveCore</span>
          </Link>
          <span className="text-sm">AI Reports</span>
        </div>
      </header>
      <main className="max-w-4xl mx-auto p-4 lg:p-8">
        <h1 className="text-2xl font-bold mb-6 flex items-center gap-2"><FileText className="w-6 h-6 text-purple-500" /> AI Report Generator</h1>

        <div className="grid md:grid-cols-2 gap-4 mb-6">
          {reportTypes.map(rt => {
            const Icon = rt.icon
            return (
              <button key={rt.name} onClick={() => setReportType(rt.name)}
                className={`p-5 rounded-2xl border text-left hover:border-purple-300 transition-all ${reportType === rt.name ? 'border-purple-500 bg-purple-50 dark:bg-purple-950' : 'bg-white dark:bg-neutral-900'}`}>
                <Icon className={`w-6 h-6 mb-3 ${reportType === rt.name ? 'text-purple-600' : 'text-muted-foreground'}`} />
                <p className="font-bold">{rt.name}</p>
                <p className="text-xs text-muted-foreground mt-1">{rt.desc}</p>
              </button>
            )
          })}
        </div>

        <Button onClick={handleGenerate} disabled={!reportType || generating} className="gap-2 bg-purple-600 mb-6">
          {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
          {generating ? 'Generating...' : 'Generate Report'}
        </Button>

        {report && (
          <div className="bg-white dark:bg-neutral-900 rounded-2xl border p-6">
            <div className="flex justify-between mb-4">
              <CheckCircle className="w-5 h-5 text-green-500" />
              <Button variant="outline" size="sm" onClick={handleDownload}><Download className="w-3 h-3 mr-1" /> Download</Button>
            </div>
            <pre className="whitespace-pre-wrap text-sm font-mono">{report}</pre>
          </div>
        )}
      </main>
    </div>
  )
}