export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const result = await pool.query(`
      SELECT sc.*, p.sku, p."sellingPrice"
      FROM "StockCount" sc
      LEFT JOIN "Product" p ON sc."productId" = p.id
      WHERE sc.id = $1 AND sc."organizationId" = $2
    `, [params.id, session.organizationId])

    if (result.rows.length === 0) {
      return NextResponse.json({ error: 'Stock count not found' }, { status: 404 })
    }

    const count = result.rows[0]
    const varianceColor = count.variance === 0 ? '#16a34a' : count.variance > 0 ? '#2563eb' : '#dc2626'

    const html = `<!DOCTYPE html>
<html>
<head>
  <title>Stock Count - ${count.number}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { text-align: center; border-bottom: 3px solid #0891b2; padding-bottom: 20px; margin-bottom: 30px; }
    .company { font-size: 28px; font-weight: bold; color: #0891b2; }
    .title { font-size: 20px; color: #6b7280; margin-top: 5px; }
    .count-number { font-size: 32px; font-weight: bold; text-align: center; color: #111827; margin: 30px 0; }
    .status-badge { display: inline-block; padding: 10px 20px; border-radius: 9999px; font-weight: bold; margin: 20px auto; text-align: center; }
    .status-pending { background: #fef3c7; color: #92400e; }
    .status-completed { background: #d1fae5; color: #065f46; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 30px 0; }
    .info-card { padding: 20px; border: 2px solid #e5e7eb; border-radius: 12px; text-align: center; }
    .info-label { font-size: 14px; color: #6b7280; margin-bottom: 8px; }
    .info-value { font-size: 24px; font-weight: bold; color: #0891b2; }
    .variance-card { grid-column: span 2; border-color: ${varianceColor}; }
    .footer { margin-top: 50px; text-align: center; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="company">IntelliWavve</div>
    <div class="title">Stock Count Report</div>
  </div>
  
  <div class="count-number">${count.number}</div>
  
  <div style="text-align: center;">
    <span class="status-badge ${count.status === 'COMPLETED' ? 'status-completed' : 'status-pending'}">${count.status}</span>
  </div>
  
  <div class="info-grid">
    <div class="info-card">
      <div class="info-label">Product</div>
      <div class="info-value" style="font-size: 18px;">${count.productName || 'N/A'}</div>
    </div>
    <div class="info-card">
      <div class="info-label">SKU</div>
      <div class="info-value" style="font-size: 18px;">${count.sku || 'N/A'}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Expected Quantity</div>
      <div class="info-value">${count.expectedQuantity || 0} units</div>
    </div>
    <div class="info-card">
      <div class="info-label">Actual Quantity</div>
      <div class="info-value">${count.actualQuantity || 0} units</div>
    </div>
    <div class="info-card variance-card">
      <div class="info-label">Variance</div>
      <div class="info-value" style="color: ${varianceColor};">${count.variance > 0 ? '+' : ''}${count.variance || 0} units</div>
    </div>
    ${count.countedBy ? `<div class="info-card">
      <div class="info-label">Counted By</div>
      <div class="info-value" style="font-size: 18px;">${count.countedBy}</div>
    </div>` : ''}
    ${count.notes ? `<div class="info-card">
      <div class="info-label">Notes</div>
      <div class="info-value" style="font-size: 16px;">${count.notes}</div>
    </div>` : ''}
  </div>
  
  <div class="footer">
    <p>Generated by IntelliWavve WaveCore ERP</p>
    <p>${new Date().toLocaleString('en-KE')}</p>
  </div>
  
  <script>window.print();</script>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="stock-count-${count.number}.html"`
      }
    })
  } catch (error) {
    console.error('Stock Counts PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}