export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const result = await pool.query(`
      SELECT t.*, p.sku, p."sellingPrice"
      FROM "Transfer" t
      LEFT JOIN "Product" p ON t."productId" = p.id
      WHERE t.id = $1 AND t."organizationId" = $2
    `, [params.id, session.organizationId])

    if (result.rows.length === 0) {
      return NextResponse.json({ error: 'Transfer not found' }, { status: 404 })
    }

    const transfer = result.rows[0]

    const html = `<!DOCTYPE html>
<html>
<head>
  <title>Transfer Receipt - ${transfer.number}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { text-align: center; border-bottom: 3px solid #7c3aed; padding-bottom: 20px; margin-bottom: 30px; }
    .company { font-size: 28px; font-weight: bold; color: #7c3aed; }
    .title { font-size: 20px; color: #6b7280; margin-top: 5px; }
    .transfer-number { font-size: 32px; font-weight: bold; text-align: center; color: #111827; margin: 30px 0; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 30px 0; }
    .info-card { padding: 20px; border: 2px solid #e5e7eb; border-radius: 12px; text-align: center; }
    .info-label { font-size: 14px; color: #6b7280; margin-bottom: 8px; }
    .info-value { font-size: 24px; font-weight: bold; color: #7c3aed; }
    .status-badge { display: inline-block; padding: 8px 16px; border-radius: 9999px; font-weight: bold; margin: 20px 0; }
    .status-pending { background: #fef3c7; color: #92400e; }
    .status-completed { background: #d1fae5; color: #065f46; }
    .footer { margin-top: 50px; text-align: center; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="company">IntelliWavve</div>
    <div class="title">Transfer Receipt</div>
  </div>
  
  <div class="transfer-number">${transfer.number}</div>
  
  <div style="text-align: center;">
    <span class="status-badge ${transfer.status === 'COMPLETED' ? 'status-completed' : 'status-pending'}">${transfer.status}</span>
  </div>
  
  <div class="info-grid">
    <div class="info-card">
      <div class="info-label">Product</div>
      <div class="info-value" style="font-size: 18px;">${transfer.productName || 'N/A'}</div>
    </div>
    <div class="info-card">
      <div class="info-label">SKU</div>
      <div class="info-value" style="font-size: 18px;">${transfer.sku || 'N/A'}</div>
    </div>
    <div class="info-card">
      <div class="info-label">From Location</div>
      <div class="info-value" style="font-size: 18px;">${transfer.fromLocation || 'N/A'}</div>
    </div>
    <div class="info-card">
      <div class="info-label">To Location</div>
      <div class="info-value" style="font-size: 18px;">${transfer.toLocation || 'N/A'}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Quantity</div>
      <div class="info-value">${transfer.quantity || 0} units</div>
    </div>
    <div class="info-card">
      <div class="info-label">Date</div>
      <div class="info-value" style="font-size: 18px;">${new Date(transfer.createdAt).toLocaleString('en-KE')}</div>
    </div>
  </div>
  
  ${transfer.notes ? `<div class="info-card" style="margin-top: 20px;">
    <div class="info-label">Notes</div>
    <div class="info-value" style="font-size: 16px;">${transfer.notes}</div>
  </div>` : ''}
  
  <div class="footer">
    <p>Generated by IntelliWavve WaveCore ERP</p>
    <p>${new Date().toLocaleString('en-KE')}</p>
  </div>
  
  <script>window.print();</script>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="transfer-${transfer.number}.html"`
      }
    })
  } catch (error) {
    console.error('Transfer PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}