export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { pool } from '@/lib/wavecore/db'
import { requireTenant } from '@/lib/wavecore/auth'

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const mrRes = await pool.query(
      `SELECT * FROM "MaintenanceRequest" WHERE id = $1 AND "organizationId" = $2`,
      [params.id, session.organizationId]
    )
    if (mrRes.rows.length === 0) return NextResponse.json({ error: 'Not found' }, { status: 404 })
    const mr = mrRes.rows[0]

    const fmtDate = (d: any) => d ? new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'
    const priorityColor = mr.priority === 'CRITICAL' ? '#dc2626'
      : mr.priority === 'HIGH' ? '#ea580c'
      : mr.priority === 'MEDIUM' ? '#ca8a04'
      : '#2563eb'
    const statusColor = mr.status === 'COMPLETED' ? '#16a34a'
      : mr.status === 'IN_PROGRESS' ? '#ca8a04'
      : mr.status === 'CANCELLED' ? '#6b7280'
      : '#dc2626'

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Maintenance ${mr.number}</title>
<style>
  @page { size: A4; margin: 15mm; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #111827; margin: 0; }
  .hdr { display: flex; justify-content: space-between; border-bottom: 4px solid ${priorityColor}; padding-bottom: 18px; margin-bottom: 24px; }
  .brand { font-size: 30px; font-weight: 800; color: ${priorityColor}; }
  .brand-sub { font-size: 12px; color: #6b7280; margin-top: 2px; }
  .doc-title h1 { font-size: 22px; margin: 0; }
  .doc-title .num { font-family: 'Courier New', monospace; font-size: 16px; color: ${priorityColor}; margin-top: 4px; font-weight: 700; }
  .meta-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; margin-bottom: 24px; }
  .meta-card { padding: 12px 14px; border: 1px solid #e5e7eb; border-radius: 10px; background: #f9fafb; }
  .meta-label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; font-weight: 700; }
  .meta-value { font-size: 15px; font-weight: 700; margin-top: 4px; }
  .section-title { font-size: 14px; font-weight: 800; color: ${priorityColor}; text-transform: uppercase; letter-spacing: 0.6px; margin: 26px 0 10px; padding-bottom: 6px; border-bottom: 2px solid ${priorityColor}22; }
  .badge { display: inline-block; padding: 6px 16px; border-radius: 16px; font-size: 12px; font-weight: 800; letter-spacing: 0.5px; }
  .desc { font-size: 13px; padding: 14px; background: #f9fafb; border-left: 3px solid ${priorityColor}; border-radius: 4px; line-height: 1.5; }
  .sign-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; margin-top: 40px; }
  .sign-box { border-top: 1.5px solid #111827; padding-top: 6px; font-size: 11px; color: #6b7280; }
  .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 10px; border-top: 1px solid #e5e7eb; padding-top: 14px; }
</style></head><body>

<div class="hdr">
  <div>
    <div class="brand">WaveCore ERP</div>
    <div class="brand-sub">Manufacturing · Maintenance Request</div>
  </div>
  <div class="doc-title">
    <h1>MAINTENANCE</h1>
    <div class="num">${mr.number || 'MR-XXXXXXXX'}</div>
  </div>
</div>

<div style="text-align:center;margin:16px 0">
  <span class="badge" style="background:${priorityColor}22;color:${priorityColor}">${mr.priority || 'MEDIUM'} PRIORITY</span>
  <span class="badge" style="background:${statusColor}22;color:${statusColor};margin-left:8px">${mr.status || 'OPEN'}</span>
</div>

<div class="meta-grid">
  <div class="meta-card"><div class="meta-label">Asset</div><div class="meta-value">${mr.assetName || '—'}</div></div>
  <div class="meta-card"><div class="meta-label">Asset Code</div><div class="meta-value">${mr.assetCode || '—'}</div></div>
  <div class="meta-card"><div class="meta-label">Type</div><div class="meta-value">${mr.type || '—'}</div></div>
  <div class="meta-card"><div class="meta-label">Assigned To</div><div class="meta-value">${mr.assignedToId || 'Unassigned'}</div></div>
  <div class="meta-card"><div class="meta-label">Requested</div><div class="meta-value">${fmtDate(mr.requestedDate)}</div></div>
  <div class="meta-card"><div class="meta-label">Completed</div><div class="meta-value">${fmtDate(mr.completedDate)}</div></div>
</div>

<div class="section-title">Description</div>
<div class="desc">${mr.description || 'No description provided.'}</div>

<div class="sign-grid">
  <div class="sign-box">Technician<br><br></div>
  <div class="sign-box">Supervisor<br><br></div>
  <div class="sign-box">Approved By<br><br></div>
</div>

<div class="footer">
  <p>Generated by WaveCore ERP · ${new Date().toLocaleString('en-GB')}</p>
  <p>© ${new Date().getFullYear()} IntelliWavve</p>
</div>

<script>window.onload = function(){ setTimeout(function(){ window.print(); }, 400); };</script>
</body></html>`

    return new NextResponse(html, { headers: { 'Content-Type': 'text/html; charset=utf-8' } })
  } catch (error) {
    console.error('Maintenance PDF error:', error)
    return NextResponse.json({ error: 'Failed' }, { status: 500 })
  }
}