export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const result = await pool.query(`
      SELECT sm.*, p.name as "productName", p.sku
      FROM "StockMove" sm
      LEFT JOIN "Product" p ON p.id = sm."productId"
      WHERE sm.id = $1 AND sm."organizationId" = $2
    `, [params.id, session.organizationId])

    if (result.rows.length === 0) {
      return NextResponse.json({ error: 'Movement not found' }, { status: 404 })
    }

    const m = result.rows[0]
    
    // Parse notes for locations and prices
    let fromLocation = 'N/A'
    let toLocation = 'N/A'
    let buyingPrice = 'N/A'
    let sellingPrice = 'N/A'
    try {
      const notesData = JSON.parse(m.notes || '{}')
      fromLocation = notesData.fromLocation || 'N/A'
      toLocation = notesData.toLocation || 'N/A'
      buyingPrice = notesData.buyingPrice || 'N/A'
      sellingPrice = notesData.sellingPrice || 'N/A'
    } catch {
      // Ignore parse errors
    }

    const html = '<!DOCTYPE html><html><head><title>Movement - ' + m.id.substring(0, 8) + '</title>' +
      '<style>body{font-family:Arial;padding:40px;max-width:800px;margin:0 auto}' +
      '.header{text-align:center;border-bottom:3px solid #16a34a;padding-bottom:20px;margin-bottom:30px}' +
      '.company{font-size:28px;font-weight:bold;color:#16a34a}' +
      '.title{font-size:18px;color:#6b7280;margin-top:5px}' +
      '.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:30px 0}' +
      '.card{padding:20px;border:2px solid #e5e7eb;border-radius:12px;text-align:center}' +
      '.label{font-size:12px;color:#6b7280;text-transform:uppercase}' +
      '.value{font-size:24px;font-weight:bold;color:#16a34a;margin-top:8px}' +
      '.footer{margin-top:40px;text-align:center;color:#9ca3af;font-size:12px;border-top:1px solid #e5e7eb;padding-top:20px}' +
      '</style></head><body>' +
      '<div class="header"><div class="company">WaveCore ERP</div><div class="title">Stock Movement Report</div></div>' +
      '<div class="grid">' +
      '<div class="card"><div class="label">Product</div><div class="value">' + (m.productName || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">SKU</div><div class="value">' + (m.sku || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">Type</div><div class="value">' + m.type + '</div></div>' +
      '<div class="card"><div class="label">Quantity</div><div class="value">' + m.quantity + '</div></div>' +
      '<div class="card"><div class="label">Buying Price</div><div class="value">KSh ' + (buyingPrice !== 'N/A' ? Number(buyingPrice).toLocaleString() : 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">Selling Price</div><div class="value">KSh ' + (sellingPrice !== 'N/A' ? Number(sellingPrice).toLocaleString() : 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">From Location</div><div class="value" style="font-size:18px">' + fromLocation + '</div></div>' +
      '<div class="card"><div class="label">To Location</div><div class="value" style="font-size:18px">' + toLocation + '</div></div>' +
      '<div class="card"><div class="label">Status</div><div class="value">' + m.status + '</div></div>' +
      '<div class="card"><div class="label">Date</div><div class="value" style="font-size:16px">' + new Date(m.date || m.createdAt).toLocaleString() + '</div></div>' +
      '</div>' +
      '<div class="footer"><p>Generated by WaveCore ERP</p><p>' + new Date().toLocaleString('en-KE') + '</p></div>' +
      '<script>window.print();</script></body></html>'

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': 'inline; filename="movement-' + m.id.substring(0, 8) + '.html"'
      }
    })
  } catch (error) {
    console.error('Movement PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}