export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const result = await pool.query(`
      SELECT *
      FROM "Offer"
      WHERE id = $1 AND "organizationId" = $2
    `, [params.id, session.organizationId])

    if (result.rows.length === 0) {
      return NextResponse.json({ error: 'Offer not found' }, { status: 404 })
    }

    const offer = result.rows[0]
    const discountDisplay = offer.discountType === 'PERCENTAGE' 
      ? `${offer.discountValue}%` 
      : `KSh ${Number(offer.discountValue).toLocaleString()}`

    const html = `<!DOCTYPE html>
<html>
<head>
  <title>Offer - ${offer.title}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { text-align: center; border-bottom: 3px solid #f59e0b; padding-bottom: 20px; margin-bottom: 30px; }
    .company { font-size: 28px; font-weight: bold; color: #f59e0b; }
    .title { font-size: 20px; color: #6b7280; margin-top: 5px; }
    .offer-title { font-size: 32px; font-weight: bold; text-align: center; color: #111827; margin: 30px 0; }
    .status-badge { display: inline-block; padding: 10px 20px; border-radius: 9999px; font-weight: bold; margin: 20px auto; text-align: center; }
    .status-active { background: #d1fae5; color: #065f46; }
    .status-expired { background: #fee2e2; color: #991b1b; }
    .status-scheduled { background: #dbeafe; color: #1e40af; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 30px 0; }
    .info-card { padding: 20px; border: 2px solid #e5e7eb; border-radius: 12px; text-align: center; }
    .info-label { font-size: 14px; color: #6b7280; margin-bottom: 8px; }
    .info-value { font-size: 24px; font-weight: bold; color: #f59e0b; }
    .footer { margin-top: 50px; text-align: center; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="company">IntelliWavve</div>
    <div class="title">Offer Details</div>
  </div>
  
  <div class="offer-title">${offer.title}</div>
  
  <div style="text-align: center;">
    <span class="status-badge status-${offer.status.toLowerCase()}">${offer.status}</span>
  </div>
  
  <div class="info-grid">
    <div class="info-card">
      <div class="info-label">Offer Number</div>
      <div class="info-value" style="font-size: 18px;">${offer.number}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Discount</div>
      <div class="info-value">${discountDisplay}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Start Date</div>
      <div class="info-value" style="font-size: 18px;">${offer.startDate ? new Date(offer.startDate).toLocaleDateString('en-KE') : 'N/A'}</div>
    </div>
    <div class="info-card">
      <div class="info-label">End Date</div>
      <div class="info-value" style="font-size: 18px;">${offer.endDate ? new Date(offer.endDate).toLocaleDateString('en-KE') : 'N/A'}</div>
    </div>
  </div>
  
  ${offer.description ? `<div class="info-card" style="margin-top: 20px;">
    <div class="info-label">Description</div>
    <div class="info-value" style="font-size: 16px;">${offer.description}</div>
  </div>` : ''}
  
  <div class="footer">
    <p>Generated by IntelliWavve WaveCore ERP</p>
    <p>${new Date().toLocaleString('en-KE')}</p>
  </div>
  
  <script>window.print();</script>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="offer-${offer.number}.html"`
      }
    })
  } catch (error) {
    console.error('Offers PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}