export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const product = await pool.query(`
      SELECT p.*, COALESCE(sq.quantity, 0) as "currentStock"
      FROM "Product" p
      LEFT JOIN "StockQuantity" sq ON sq."productId" = p.id
      WHERE p.id = $1 AND p."organizationId" = $2
    `, [params.id, session.organizationId])

    if (product.rows.length === 0) {
      return NextResponse.json({ error: 'Product not found' }, { status: 404 })
    }

    const p = product.rows[0]
    const created = new Date(p.createdAt)
    const now = new Date()
    const daysInInventory = Math.floor((now.getTime() - created.getTime()) / (1000 * 60 * 60 * 24))

    const html = '<!DOCTYPE html><html><head><title>Stock Aging - ' + p.name + '</title>' +
      '<style>body{font-family:Arial;padding:40px;max-width:800px;margin:0 auto}' +
      '.header{text-align:center;border-bottom:3px solid #f59e0b;padding-bottom:20px;margin-bottom:30px}' +
      '.company{font-size:28px;font-weight:bold;color:#f59e0b}' +
      '.name{font-size:32px;font-weight:bold;text-align:center;margin:20px 0}' +
      '.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:30px 0}' +
      '.card{padding:20px;border:2px solid #e5e7eb;border-radius:12px;text-align:center}' +
      '.label{font-size:12px;color:#6b7280;text-transform:uppercase}' +
      '.value{font-size:24px;font-weight:bold;color:#f59e0b;margin-top:8px}' +
      '.warning{color:#dc2626}.safe{color:#16a34a}' +
      '.footer{margin-top:40px;text-align:center;color:#9ca3af;font-size:12px;border-top:1px solid #e5e7eb;padding-top:20px}' +
      '</style></head><body>' +
      '<div class="header"><div class="company">WaveCore ERP</div><p>Stock Aging Report</p></div>' +
      '<div class="name">' + p.name + '</div>' +
      '<div class="grid">' +
      '<div class="card"><div class="label">SKU</div><div class="value">' + (p.sku || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">Current Stock</div><div class="value">' + p.currentStock + '</div></div>' +
      '<div class="card"><div class="label">Days in Inventory</div><div class="value ' + (daysInInventory > 90 ? 'warning' : 'safe') + '">' + daysInInventory + '</div></div>' +
      '<div class="card"><div class="label">Created Date</div><div class="value" style="font-size:16px">' + new Date(p.createdAt).toLocaleDateString() + '</div></div>' +
      '<div class="card"><div class="label">Stock Status</div><div class="value ' + (daysInInventory > 180 ? 'warning' : daysInInventory > 90 ? 'warning' : 'safe') + '">' + (daysInInventory > 180 ? 'DEAD STOCK' : daysInInventory > 90 ? 'SLOW MOVING' : 'HEALTHY') + '</div></div>' +
      '</div>' +
      '<div class="footer"><p>Generated by WaveCore ERP</p><p>' + new Date().toLocaleString('en-KE') + '</p></div>' +
      '<script>window.print();</script></body></html>'

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': 'inline; filename="aging-' + (p.sku || p.id) + '.html"'
      }
    })
  } catch (error) {
    console.error('Aging PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}