export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { pool } from '@/lib/wavecore/db'
import { requireTenant } from '@/lib/wavecore/auth'
import { guardHR } from '@/lib/wavecore/guard'

function esc(s: any): string {
  return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!))
}
function fmtDate(d: any): string {
  if (!d) return '—'
  try { return new Date(d).toLocaleString('en-GB') } catch { return '—' }
}

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const guard = await guardHR(request, 'HR_EXPORT')
    if (guard.deny) return guard.response!

    const res = await pool.query(
      `SELECT * FROM "CannedResponse" WHERE id = $1 AND "organizationId" = $2`,
      [params.id, session.organizationId]
    )
    if (res.rows.length === 0) return NextResponse.json({ error: 'Not found' }, { status: 404 })
    const t = res.rows[0]

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Template — ${esc(t.title)}</title>
<style>
  @page { size: A4 portrait; margin: 15mm; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #111827; margin: 0; }
  .hdr { display: flex; justify-content: space-between; border-bottom: 4px solid #7c3aed; padding-bottom: 16px; margin-bottom: 20px; }
  .brand { font-size: 26px; font-weight: 800; color: #7c3aed; }
  .brand-sub { font-size: 11px; color: #6b7280; margin-top: 2px; }
  .doc-title h1 { font-size: 18px; margin: 0; }
  .doc-title .num { font-family: 'Courier New', monospace; font-size: 11px; color: #7c3aed; margin-top: 4px; font-weight: 700; }
  .section-title { font-size: 12px; font-weight: 800; color: #7c3aed; text-transform: uppercase; letter-spacing: 0.6px; margin: 20px 0 10px; padding-bottom: 4px; border-bottom: 2px solid #ede9fe; }
  .grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; margin-bottom: 16px; }
  .field { padding: 8px 10px; border: 1px solid #e5e7eb; border-radius: 6px; }
  .field-label { font-size: 9px; text-transform: uppercase; color: #6b7280; letter-spacing: 0.5px; font-weight: 700; }
  .field-value { font-size: 12px; color: #111827; margin-top: 2px; font-weight: 600; word-break: break-word; }
  .body-box { padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; background: #f9fafb; }
  .body-text { font-size: 12px; color: #374151; line-height: 1.6; white-space: pre-wrap; margin: 0; }
  .footer { margin-top: 30px; text-align: center; color: #9ca3af; font-size: 10px; border-top: 1px solid #e5e7eb; padding-top: 12px; }
</style></head><body>

<div class="hdr">
  <div><div class="brand">WaveCore ERP</div><div class="brand-sub">Helpdesk · Response Template</div></div>
  <div class="doc-title"><h1>RESPONSE TEMPLATE</h1><div class="num">${esc((t.id || '').slice(0, 8).toUpperCase())}</div></div>
</div>

<div class="section-title">Details</div>
<div class="grid">
  <div class="field"><div class="field-label">Title</div><div class="field-value">${esc(t.title)}</div></div>
  <div class="field"><div class="field-label">Category</div><div class="field-value">${esc(t.category || '—')}</div></div>
  <div class="field"><div class="field-label">Shortcut</div><div class="field-value" style="font-family:monospace">${esc(t.shortcut || '—')}</div></div>
  <div class="field"><div class="field-label">Created</div><div class="field-value" style="font-size:11px">${fmtDate(t.createdAt)}</div></div>
  <div class="field"><div class="field-label">Word Count</div><div class="field-value">${esc((String(t.body || '').trim().split(/\s+/).filter(Boolean)).length)}</div></div>
  <div class="field"><div class="field-label">Char Count</div><div class="field-value">${esc(String(t.body || '').length)}</div></div>
</div>

<div class="section-title">Body</div>
<div class="body-box"><p class="body-text">${esc(t.body || 'No content.')}</p></div>

<div class="footer"><p>Generated by WaveCore ERP · © ${new Date().getFullYear()} IntelliWavve</p></div>

<script>window.onload = function(){ setTimeout(function(){ window.print(); }, 400); };</script>
</body></html>`

    return new NextResponse(html, { headers: { 'Content-Type': 'text/html; charset=utf-8' } })
  } catch (error) {
    console.error('Template PDF error:', error)
    return NextResponse.json({ error: 'Something went wrong. Please try again.' }, { status: 500 })
  }
}