export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { pool } from '@/lib/wavecore/db'
import { requireTenant } from '@/lib/wavecore/auth'
import { guardHR } from '@/lib/wavecore/guard'

function esc(s: any): string {
  return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!))
}
function fmtDate(d: any): string {
  if (!d) return '—'
  try { return new Date(d).toLocaleString('en-GB') } catch { return '—' }
}

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const guard = await guardHR(request, 'HR_EXPORT')
    if (guard.deny) return guard.response!

    const res = await pool.query(
      `SELECT * FROM "SLAPolicy" WHERE id = $1 AND "organizationId" = $2`,
      [params.id, session.organizationId]
    )
    if (res.rows.length === 0) return NextResponse.json({ error: 'Not found' }, { status: 404 })
    const p = res.rows[0]

    const priorityColor = (x: string) =>
      x === 'URGENT' ? '#dc2626' :
      x === 'HIGH' ? '#ea580c' :
      x === 'MEDIUM' ? '#0891b2' : '#6b7280'

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>SLA Policy — ${esc(p.name)}</title>
<style>
  @page { size: A4 portrait; margin: 15mm; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #111827; margin: 0; }
  .hdr { display: flex; justify-content: space-between; border-bottom: 4px solid #ea580c; padding-bottom: 16px; margin-bottom: 20px; }
  .brand { font-size: 26px; font-weight: 800; color: #ea580c; }
  .brand-sub { font-size: 11px; color: #6b7280; margin-top: 2px; }
  .doc-title h1 { font-size: 18px; margin: 0; }
  .doc-title .num { font-family: 'Courier New', monospace; font-size: 11px; color: #ea580c; margin-top: 4px; font-weight: 700; }
  .section-title { font-size: 12px; font-weight: 800; color: #ea580c; text-transform: uppercase; letter-spacing: 0.6px; margin: 20px 0 10px; padding-bottom: 4px; border-bottom: 2px solid #ffedd5; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 16px; }
  .field { padding: 8px 10px; border: 1px solid #e5e7eb; border-radius: 6px; }
  .field-label { font-size: 9px; text-transform: uppercase; color: #6b7280; letter-spacing: 0.5px; font-weight: 700; }
  .field-value { font-size: 12px; color: #111827; margin-top: 2px; font-weight: 600; word-break: break-word; }
  .body-box { padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; background: #f9fafb; }
  .body-text { font-size: 12px; color: #374151; line-height: 1.6; white-space: pre-wrap; margin: 0; }
  .footer { margin-top: 30px; text-align: center; color: #9ca3af; font-size: 10px; border-top: 1px solid #e5e7eb; padding-top: 12px; }
</style></head><body>

<div class="hdr">
  <div><div class="brand">WaveCore ERP</div><div class="brand-sub">Helpdesk · SLA Policy</div></div>
  <div class="doc-title"><h1>SLA POLICY</h1><div class="num">${esc((p.id || '').slice(0, 8).toUpperCase())}</div></div>
</div>

<div class="section-title">Policy</div>
<div class="grid">
  <div class="field"><div class="field-label">Name</div><div class="field-value">${esc(p.name)}</div></div>
  <div class="field"><div class="field-label">Priority</div><div class="field-value" style="color:${priorityColor(p.priority)}">${esc(p.priority || '—')}</div></div>
  <div class="field"><div class="field-label">First Response</div><div class="field-value">${esc(p.firstResponseHours != null ? p.firstResponseHours + ' hours' : '—')}</div></div>
  <div class="field"><div class="field-label">Resolution</div><div class="field-value">${esc(p.resolutionHours != null ? p.resolutionHours + ' hours' : '—')}</div></div>
  <div class="field"><div class="field-label">Business Hours Only</div><div class="field-value">${p.businessHoursOnly ? 'Yes' : 'No'}</div></div>
  <div class="field"><div class="field-label">Status</div><div class="field-value" style="color:${p.active ? '#16a34a' : '#6b7280'}">${p.active ? 'ACTIVE' : 'INACTIVE'}</div></div>
  <div class="field"><div class="field-label">Created</div><div class="field-value" style="font-size:11px">${fmtDate(p.createdAt)}</div></div>
  <div class="field"><div class="field-label">Updated</div><div class="field-value" style="font-size:11px">${fmtDate(p.updatedAt)}</div></div>
</div>

<div class="section-title">Description</div>
<div class="body-box"><p class="body-text">${esc(p.description || 'No description provided.')}</p></div>

<div class="footer"><p>Generated by WaveCore ERP · © ${new Date().getFullYear()} IntelliWavve</p></div>

<script>window.onload = function(){ setTimeout(function(){ window.print(); }, 400); };</script>
</body></html>`

    return new NextResponse(html, { headers: { 'Content-Type': 'text/html; charset=utf-8' } })
  } catch (error) {
    console.error('SLA policy PDF error:', error)
    return NextResponse.json({ error: 'Something went wrong. Please try again.' }, { status: 500 })
  }
}