export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(request: NextRequest) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { searchParams } = new URL(request.url)
    const type = searchParams.get('type') || 'movement'
    const id = searchParams.get('id')
    const productId = searchParams.get('productId')
    const orgId = session.organizationId

    let title = 'Anomaly Report'
    let rows = ''

    if (type === 'movement' && id) {
      const result = await pool.query(`SELECT sm.*, p.name as "productName" FROM "StockMove" sm JOIN "Product" p ON sm."productId" = p.id WHERE sm.id = $1 AND sm."organizationId" = $2`, [id, orgId])
      const m = result.rows[0]
      if (!m) return NextResponse.json({ error: 'Not found' }, { status: 404 })
      title = 'Movement Anomaly: ' + m.productName
      rows = '<div class="row"><b>Product:</b> ' + m.productName + '</div>' +
             '<div class="row"><b>Quantity:</b> ' + m.quantity + '</div>' +
             '<div class="row"><b>Type:</b> ' + (m.type || 'N/A') + '</div>' +
             '<div class="row"><b>Date:</b> ' + new Date(m.createdAt).toLocaleString() + '</div>'
    } else if (type === 'negative' && productId) {
      const result = await pool.query(`SELECT p.name, COALESCE(sq.quantity,0) as qty FROM "Product" p LEFT JOIN "StockQuantity" sq ON sq."productId" = p.id WHERE p.id = $1 AND p."organizationId" = $2`, [productId, orgId])
      const n = result.rows[0]
      if (!n) return NextResponse.json({ error: 'Not found' }, { status: 404 })
      title = 'Negative Stock: ' + n.name
      rows = '<div class="row"><b>Product:</b> ' + n.name + '</div>' +
             '<div class="row"><b>Quantity:</b> ' + n.qty + '</div>'
    } else if (type === 'shrinkage' && productId) {
      const result = await pool.query(`SELECT p.name, SUM(ABS(sm.quantity)) as total FROM "StockMove" sm JOIN "Product" p ON sm."productId" = p.id WHERE sm."productId" = $1 AND sm."organizationId" = $2 AND sm.type = 'ADJUSTMENT' AND sm.quantity < 0 GROUP BY p.name`, [productId, orgId])
      const s = result.rows[0]
      if (!s) return NextResponse.json({ error: 'Not found' }, { status: 404 })
      title = 'Shrinkage: ' + s.name
      rows = '<div class="row"><b>Product:</b> ' + s.name + '</div>' +
             '<div class="row"><b>Total Shrinkage:</b> ' + s.total + ' units</div>'
    }

    const html = '<!DOCTYPE html><html><head><title>' + title + '</title>' +
      '<style>body{font-family:Arial;padding:40px;max-width:800px;margin:0 auto}' +
      '.header{text-align:center;border-bottom:3px solid #dc2626;padding-bottom:20px;margin-bottom:30px}' +
      '.company{font-size:28px;font-weight:bold;color:#dc2626}' +
      '.title{font-size:18px;color:#6b7280;margin-top:5px}' +
      '.row{padding:15px;border-bottom:1px solid #e5e7eb;font-size:16px}' +
      '.footer{margin-top:40px;text-align:center;color:#9ca3af;font-size:12px;border-top:1px solid #e5e7eb;padding-top:20px}' +
      '</style></head><body>' +
      '<div class="header"><div class="company">WaveCore ERP</div><div class="title">Anomaly Detection Report</div></div>' +
      '<div style="text-align:center;font-size:22px;font-weight:bold;margin:20px 0;color:#dc2626">' + title + '</div>' +
      rows +
      '<div class="footer"><p>Generated by WaveCore ERP</p><p>' + new Date().toLocaleString('en-KE') + '</p></div>' +
      '<script>window.print();</script></body></html>'

    return new NextResponse(html, {
      headers: { 'Content-Type': 'text/html' }
    })
  } catch (error) {
    console.error('Anomaly PDF error:', error)
    return NextResponse.json({ error: 'Failed' }, { status: 500 })
  }
}