export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const result = await pool.query(
      'SELECT * FROM "PurchaseOrder" WHERE id = $1 AND "organizationId" = $2',
      [params.id, session.organizationId]
    )

    if (result.rows.length === 0) {
      return NextResponse.json({ error: 'Purchase order not found' }, { status: 404 })
    }

    const po = result.rows[0]

    const html = '<!DOCTYPE html><html><head><title>Purchase Order - ' + po.id.substring(0, 8) + '</title>' +
      '<style>body{font-family:Arial;padding:40px;max-width:800px;margin:0 auto}' +
      '.header{text-align:center;border-bottom:3px solid #ea580c;padding-bottom:20px;margin-bottom:30px}' +
      '.company{font-size:28px;font-weight:bold;color:#ea580c}' +
      '.title{font-size:18px;color:#6b7280;margin-top:5px}' +
      '.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:30px 0}' +
      '.card{padding:20px;border:2px solid #e5e7eb;border-radius:12px;text-align:center}' +
      '.label{font-size:12px;color:#6b7280;text-transform:uppercase}' +
      '.value{font-size:22px;font-weight:bold;color:#ea580c;margin-top:8px}' +
      '.footer{margin-top:40px;text-align:center;color:#9ca3af;font-size:12px;border-top:1px solid #e5e7eb;padding-top:20px}' +
      '</style></head><body>' +
      '<div class="header"><div class="company">WaveCore ERP</div><div class="title">Purchase Order</div></div>' +
      '<div class="grid">' +
      '<div class="card"><div class="label">PO Number</div><div class="value" style="font-size:16px">PO-' + po.id.substring(0, 8) + '</div></div>' +
      '<div class="card"><div class="label">Supplier</div><div class="value" style="font-size:16px">' + (po.supplierName || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">Amount</div><div class="value">KSh ' + Number(po.amount || 0).toLocaleString() + '</div></div>' +
      '<div class="card"><div class="label">Status</div><div class="value">' + (po.status || 'PENDING') + '</div></div>' +
      '<div class="card"><div class="label">Date Created</div><div class="value" style="font-size:14px">' + new Date(po.createdAt).toLocaleString() + '</div></div>' +
      '</div>' +
      '<div class="footer"><p>Generated by WaveCore ERP</p><p>' + new Date().toLocaleString('en-KE') + '</p></div>' +
      '<script>window.print();</script></body></html>'

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': 'inline; filename="po-' + po.id.substring(0, 8) + '.html"'
      }
    })
  } catch (error) {
    console.error('PO PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}