export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const result = await pool.query(`
      SELECT 
        p.*,
        (p."sellingPrice" - COALESCE(p."costPrice", 0)) as "profitPerUnit",
        ((p."sellingPrice" - COALESCE(p."costPrice", 0)) * p.stock_level) as "potentialProfit",
        CASE 
          WHEN p."sellingPrice" > 0 THEN ((p."sellingPrice" - COALESCE(p."costPrice", 0)) / p."sellingPrice") * 100
          ELSE 0
        END as "profitMargin"
      FROM "Product" p
      WHERE p.id = $1 AND p."organizationId" = $2
    `, [params.id, session.organizationId])

    if (result.rows.length === 0) {
      return NextResponse.json({ error: 'Product not found' }, { status: 404 })
    }

    const product = result.rows[0]

    const html = `<!DOCTYPE html>
<html>
<head>
  <title>Profit Report - ${product.name}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { text-align: center; border-bottom: 3px solid #16a34a; padding-bottom: 20px; margin-bottom: 30px; }
    .company { font-size: 28px; font-weight: bold; color: #16a34a; }
    .title { font-size: 20px; color: #6b7280; margin-top: 5px; }
    .product-name { font-size: 32px; font-weight: bold; text-align: center; color: #111827; margin: 30px 0; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 30px 0; }
    .info-card { padding: 20px; border: 2px solid #e5e7eb; border-radius: 12px; text-align: center; }
    .info-label { font-size: 14px; color: #6b7280; margin-bottom: 8px; }
    .info-value { font-size: 24px; font-weight: bold; color: #16a34a; }
    .footer { margin-top: 50px; text-align: center; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="company">IntelliWavve</div>
    <div class="title">Profit Analysis Report</div>
  </div>
  
  <div class="product-name">${product.name}</div>
  
  <div class="info-grid">
    <div class="info-card">
      <div class="info-label">Cost Price</div>
      <div class="info-value">KSh ${Number(product.costPrice || 0).toLocaleString()}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Selling Price</div>
      <div class="info-value">KSh ${Number(product.sellingPrice || 0).toLocaleString()}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Profit Per Unit</div>
      <div class="info-value">KSh ${Number(product.profitPerUnit || 0).toLocaleString()}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Profit Margin</div>
      <div class="info-value">${Number(product.profitMargin || 0).toFixed(2)}%</div>
    </div>
    <div class="info-card" style="grid-column: span 2; background: #f0fdf4; border-color: #16a34a;">
      <div class="info-label">Potential Profit (All Stock)</div>
      <div class="info-value" style="font-size: 32px; color: #16a34a;">KSh ${Number(product.potentialProfit || 0).toLocaleString()}</div>
    </div>
  </div>
  
  <div class="footer">
    <p>Generated by IntelliWavve WaveCore ERP</p>
    <p>${new Date().toLocaleString('en-KE')}</p>
  </div>
  
  <script>window.print();</script>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="profit-${product.name}.html"`
      }
    })
  } catch (error) {
    console.error('Profit PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}