export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(request: NextRequest) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const orgId = session.organizationId
    const { searchParams } = new URL(request.url)
    const method = searchParams.get('method') || 'WEIGHTED_AVERAGE'

    const products = await pool.query(`
      SELECT p.*, COALESCE(sq.quantity, 0) as "currentStock",
        p."costPrice" * COALESCE(sq.quantity, 0) as "totalCost",
        p."sellingPrice" * COALESCE(sq.quantity, 0) as "totalSellingValue"
      FROM "Product" p
      LEFT JOIN "StockQuantity" sq ON sq."productId" = p.id
      WHERE p."organizationId" = $1 ORDER BY p.name ASC
    `, [orgId])

    const totalValue = products.rows.reduce((s, p) => s + Number(p.totalCost || 0), 0)
    const totalSelling = products.rows.reduce((s, p) => s + Number(p.totalSellingValue || 0), 0)

    const html = '<!DOCTYPE html><html><head><title>Valuation Report</title>' +
      '<style>body{font-family:Arial;padding:40px;max-width:800px;margin:0 auto}' +
      '.header{text-align:center;border-bottom:3px solid #059669;padding-bottom:20px;margin-bottom:30px}' +
      '.company{font-size:28px;font-weight:bold;color:#059669}' +
      '.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:30px 0}' +
      '.card{padding:20px;border:2px solid #e5e7eb;border-radius:12px;text-align:center}' +
      '.label{font-size:12px;color:#6b7280;text-transform:uppercase}' +
      '.value{font-size:24px;font-weight:bold;color:#059669;margin-top:8px}' +
      '.footer{margin-top:40px;text-align:center;color:#9ca3af;font-size:12px;border-top:1px solid #e5e7eb;padding-top:20px}' +
      '</style></head><body>' +
      '<div class="header"><div class="company">WaveCore ERP</div><p>Inventory Valuation Report (' + method + ')</p></div>' +
      '<div class="grid">' +
      '<div class="card"><div class="label">Total Products</div><div class="value">' + products.rows.length + '</div></div>' +
      '<div class="card"><div class="label">Total Units</div><div class="value">' + products.rows.reduce((s, p) => s + Number(p.currentStock || 0), 0) + '</div></div>' +
      '<div class="card"><div class="label">Total Cost Value</div><div class="value">KSh ' + totalValue.toLocaleString() + '</div></div>' +
      '<div class="card"><div class="label">Total Selling Value</div><div class="value">KSh ' + totalSelling.toLocaleString() + '</div></div>' +
      '<div class="card"><div class="label">Potential Profit</div><div class="value">KSh ' + (totalSelling - totalValue).toLocaleString() + '</div></div>' +
      '</div>' +
      '<div class="footer"><p>Generated by WaveCore ERP</p><p>' + new Date().toLocaleString('en-KE') + '</p></div>' +
      '<script>window.print();</script></body></html>'

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': 'inline; filename="valuation-report.html"'
      }
    })
  } catch (error) {
    console.error('Valuation PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}