export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const result = await pool.query(`
      SELECT t.*, p.sku
      FROM "Transfer" t
      LEFT JOIN "Product" p ON p.id = t."productId"
      WHERE t.id = $1 AND t."organizationId" = $2
    `, [params.id, session.organizationId])

    if (result.rows.length === 0) {
      return NextResponse.json({ error: 'Transfer not found' }, { status: 404 })
    }

    const t = result.rows[0]

    let buyingPrice = 0
    let sellingPrice = 0
    try {
      const n = JSON.parse(t.notes || '{}')
      buyingPrice = Number(n.buyingPrice || 0)
      sellingPrice = Number(n.sellingPrice || 0)
    } catch (e) {}

    const html = '<!DOCTYPE html><html><head><title>Transfer - ' + t.number + '</title>' +
      '<style>body{font-family:Arial;padding:40px;max-width:800px;margin:0 auto}' +
      '.header{text-align:center;border-bottom:3px solid #7c3aed;padding-bottom:20px;margin-bottom:30px}' +
      '.company{font-size:28px;font-weight:bold;color:#7c3aed}' +
      '.title{font-size:18px;color:#6b7280;margin-top:5px}' +
      '.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:30px 0}' +
      '.card{padding:20px;border:2px solid #e5e7eb;border-radius:12px;text-align:center}' +
      '.label{font-size:12px;color:#6b7280;text-transform:uppercase}' +
      '.value{font-size:22px;font-weight:bold;color:#7c3aed;margin-top:8px}' +
      '.footer{margin-top:40px;text-align:center;color:#9ca3af;font-size:12px;border-top:1px solid #e5e7eb;padding-top:20px}' +
      '</style></head><body>' +
      '<div class="header"><div class="company">WaveCore ERP</div><div class="title">Transfer Receipt</div></div>' +
      '<div class="grid">' +
      '<div class="card"><div class="label">Number</div><div class="value" style="font-size:18px">' + t.number + '</div></div>' +
      '<div class="card"><div class="label">Product</div><div class="value" style="font-size:16px">' + (t.productName || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">From</div><div class="value" style="font-size:16px">' + (t.fromLocation || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">To</div><div class="value" style="font-size:16px">' + (t.toLocation || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">Quantity</div><div class="value">' + t.quantity + '</div></div>' +
      '<div class="card"><div class="label">Buying Price</div><div class="value">KSh ' + buyingPrice.toLocaleString() + '</div></div>' +
      '<div class="card"><div class="label">Selling Price</div><div class="value">KSh ' + sellingPrice.toLocaleString() + '</div></div>' +
      '<div class="card"><div class="label">Status</div><div class="value">' + t.status + '</div></div>' +
      '</div>' +
      '<div class="footer"><p>Generated by WaveCore ERP</p><p>' + new Date().toLocaleString('en-KE') + '</p></div>' +
      '<script>window.print();</script></body></html>'

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': 'inline; filename="transfer-' + t.number + '.html"'
      }
    })
  } catch (error) {
    console.error('Transfer PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}