export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { requireTenant } from '@/lib/wavecore/auth'
import { pool } from '@/lib/wavecore/db'

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await requireTenant(request)
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const product = await pool.query(`
      SELECT p.*, COALESCE(sq.quantity, 0) as "currentStock",
        p."sellingPrice" * COALESCE(sq.quantity, 0) as "stockValue"
      FROM "Product" p
      LEFT JOIN "StockQuantity" sq ON sq."productId" = p.id
      WHERE p.id = $1 AND p."organizationId" = $2
    `, [params.id, session.organizationId])

    if (product.rows.length === 0) {
      return NextResponse.json({ error: 'Product not found' }, { status: 404 })
    }

    const p = product.rows[0]

    // Calculate ABC class
    const totalValueResult = await pool.query(`
      SELECT COALESCE(SUM(p."sellingPrice" * COALESCE(sq.quantity, 0)), 0) as total
      FROM "Product" p LEFT JOIN "StockQuantity" sq ON sq."productId" = p.id
      WHERE p."organizationId" = $1
    `, [session.organizationId])
    const totalValue = Number(totalValueResult.rows[0]?.total || 0)

    // Get all products sorted by value
    const allProducts = await pool.query(`
      SELECT p.id, p."sellingPrice" * COALESCE(sq.quantity, 0) as "stockValue"
      FROM "Product" p LEFT JOIN "StockQuantity" sq ON sq."productId" = p.id
      WHERE p."organizationId" = $1 ORDER BY "stockValue" DESC
    `, [session.organizationId])

    let cumulative = 0
    let abcClass = 'C'
    for (const prod of allProducts.rows) {
      cumulative += Number(prod.stockValue || 0)
      if (prod.id === params.id) {
        const pct = totalValue > 0 ? (cumulative / totalValue) * 100 : 0
        if (pct <= 80) abcClass = 'A'
        else if (pct <= 95) abcClass = 'B'
        break
      }
    }

    const html = '<!DOCTYPE html><html><head><title>ABC/XYZ - ' + p.name + '</title>' +
      '<style>body{font-family:Arial;padding:40px;max-width:800px;margin:0 auto}' +
      '.header{text-align:center;border-bottom:3px solid #7c3aed;padding-bottom:20px;margin-bottom:30px}' +
      '.company{font-size:28px;font-weight:bold;color:#7c3aed}' +
      '.name{font-size:32px;font-weight:bold;text-align:center;margin:20px 0}' +
      '.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:30px 0}' +
      '.card{padding:20px;border:2px solid #e5e7eb;border-radius:12px;text-align:center}' +
      '.label{font-size:12px;color:#6b7280;text-transform:uppercase}' +
      '.value{font-size:24px;font-weight:bold;color:#7c3aed;margin-top:8px}' +
      '.classA{color:#16a34a}.classB{color:#d97706}.classC{color:#dc2626}' +
      '.footer{margin-top:40px;text-align:center;color:#9ca3af;font-size:12px;border-top:1px solid #e5e7eb;padding-top:20px}' +
      '</style></head><body>' +
      '<div class="header"><div class="company">WaveCore ERP</div><p>ABC/XYZ Analysis Report</p></div>' +
      '<div class="name">' + p.name + '</div>' +
      '<div class="grid">' +
      '<div class="card"><div class="label">SKU</div><div class="value">' + (p.sku || 'N/A') + '</div></div>' +
      '<div class="card"><div class="label">ABC Class</div><div class="value class' + abcClass + '">' + abcClass + '</div></div>' +
      '<div class="card"><div class="label">Stock Value</div><div class="value">KSh ' + Number(p.stockValue || 0).toLocaleString() + '</div></div>' +
      '<div class="card"><div class="label">Current Stock</div><div class="value">' + p.currentStock + '</div></div>' +
      '<div class="card"><div class="label">Selling Price</div><div class="value">KSh ' + Number(p.sellingPrice || 0).toLocaleString() + '</div></div>' +
      '<div class="card"><div class="label">Min Stock</div><div class="value">' + (p.minStock || 10) + '</div></div>' +
      '</div>' +
      '<div class="footer"><p>Generated by WaveCore ERP</p><p>' + new Date().toLocaleString('en-KE') + '</p></div>' +
      '<script>window.print();</script></body></html>'

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': 'inline; filename="abc-xyz-' + (p.sku || p.id) + '.html"'
      }
    })
  } catch (error) {
    console.error('ABC/XYZ PDF error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}